@startuml
!theme toy

!unquoted procedure $element($alias, $description="", $label="", $technology="", $size=12, $colour="green")
rectangle $alias as "
<color:$colour>alias <<$alias>> </color>
 =>
$description"
!endprocedure

package "Core" {
  package BaseTypes
  {
    enum ReadStatus {
      BAD_FRAME
      OK
    }

    struct Frame {
    + frame_counter : std::uint16_t
    + source_id: std::uint8_t
    + payload : std::variant<std::uint8_t, std::int16_t, std::int32_t, IEEE_754_float>
    }

    struct Signal {
    + frame_counter : std::uint16_t
    + source_id: std::uint8_t
    + signal : IEEE_754_float normalized
    }
  }

  interface IDataSource {
  +read(data : char* , size: int) : int
  }

  class DataSource {
  +read(data : char* , size: int) : int
  }

  $element(FrameHandler, "std::function<void(frame : const Frame&, status : ReadStatus)>", $size=10, $technology="c++")

  class FrameReader {
  +FrameReader(source: IDataSource&, handler : FrameHandler&)
  -m_frame_handler : FrameHandler
  -m_thread : std::thread
  -m_source : IDataSource&
  }

  $element(SignalHandler, "std::function<void(frame : const Signal&, status : ReadStatus)>", $size=10, $technology="c++")

  class FrameProcessor {
  +FrameProcessor(handler : SignalHandler&)
  +process_frame(output : Frame&, status : ReadStatus) : void
  -m_thread : std::thread
  -m_handler : SignalHandler
  }


  class Converter {
  +convert(input : Frame, status: ReadStatus) : Signal
  }

  ' Client listener
  interface ISignalReceiver {
  +process(signal: const Signal&, status: ReadStatus): void
  }

  class SignalStorage {
  +process(signal: const Signal&, status: ReadStatus): void
  }

  class SignalLogger {
  +process(signal: const Signal&, status: ReadStatus): void
  }


  class Statistics
  {
  +add_frame(frame: const Frame&, ReadStatus : status) : void
  }

  class Provider {
  +registerClient(client: IClient*):void
  }
}


package Simulation
{
class TestDataSource {
+read(data : char* , size: int) : int
}
}

IDataSource <|.. DataSource
IDataSource <|.. TestDataSource
FrameReader -up-o IDataSource
FrameReader -up-o FrameHandler
FrameProcessor ..> Converter
FrameProcessor -up-o SignalHandler
Provider "1" --* "1 for each source" FrameProcessor
Provider --* FrameReader
Provider --o IDataSource
Provider "1" --o "n" ISignalReceiver
Provider ..|> SignalHandler
Provider ..|> FrameHandler
SignalStorage .up.|> ISignalReceiver
SignalLogger .up.|> ISignalReceiver
Statistics .up.|> ISignalReceiver
@enduml
